/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Pre_FRAMS;

import java.awt.CardLayout;
import java.awt.Color;
import java.awt.Frame;
import java.awt.Toolkit;
import java.awt.image.BufferedImage;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.SwingUtilities;

/**
 *
 * @author Ray24
 */
public class Admin_Main extends javax.swing.JFrame {

    /**
     * Creates new form Admin_Main
     */
    String adminid=null;
    CardLayout card=new CardLayout();
    Student_dtls st=null;
    Subject_dtls sub=null;
    Faculty_dtls fac=null;
    Department_dtls dept=null;
    User_dtls user=null;
    Schedual_dtls schedual=null;
    Webcam_dtls webcam=null;
    ReportGen rptgn=null;
    public Admin_Main() {
        initComponents();
        
        panel_main.setLayout(card);
        st=new Student_dtls();
        sub=new Subject_dtls();
        fac=new Faculty_dtls();
        dept=new Department_dtls();
        user=new User_dtls();
        schedual=new Schedual_dtls(); 
        webcam=new Webcam_dtls();
        rptgn=new ReportGen();
        
        panel_main.add(webcam,"Webcam_dtls");
        panel_main.add(rptgn,"ReportGen");
        panel_main.add(st,"Student_dtls");
        panel_main.add(dept,"Department_dtls");
        panel_main.add(fac,"Faculty_dtls");
        panel_main.add(sub,"Subject_dtls");
        panel_main.add(user,"User_dtls");
        panel_main.add(schedual,"Schedual_dtls");
        //new mainserver();
    
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_main = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        dbmgmt = new javax.swing.JMenu();
        studentmgmt = new javax.swing.JMenuItem();
        submgmt = new javax.swing.JMenuItem();
        facultymgmt = new javax.swing.JMenuItem();
        deparmentmgmt = new javax.swing.JMenuItem();
        usermanagement = new javax.swing.JMenuItem();
        schedualmanagement = new javax.swing.JMenuItem();
        webcams = new javax.swing.JMenu();
        allwebcams = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        aggregate_att = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Welcome");
        setName("Admin_main"); // NOI18N
        setPreferredSize(new java.awt.Dimension(930, 525));
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
                formWindowGainedFocus(evt);
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        panel_main.setPreferredSize(new java.awt.Dimension(930, 504));

        javax.swing.GroupLayout panel_mainLayout = new javax.swing.GroupLayout(panel_main);
        panel_main.setLayout(panel_mainLayout);
        panel_mainLayout.setHorizontalGroup(
            panel_mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 930, Short.MAX_VALUE)
        );
        panel_mainLayout.setVerticalGroup(
            panel_mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 504, Short.MAX_VALUE)
        );

        dbmgmt.setText("Database Management");

        studentmgmt.setText("Student Management");
        studentmgmt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                studentmgmtActionPerformed(evt);
            }
        });
        dbmgmt.add(studentmgmt);

        submgmt.setText("Subject Management");
        submgmt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submgmtActionPerformed(evt);
            }
        });
        dbmgmt.add(submgmt);

        facultymgmt.setText("Faculty Management");
        facultymgmt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                facultymgmtActionPerformed(evt);
            }
        });
        dbmgmt.add(facultymgmt);

        deparmentmgmt.setText("Department Management");
        deparmentmgmt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deparmentmgmtActionPerformed(evt);
            }
        });
        dbmgmt.add(deparmentmgmt);

        usermanagement.setText("User Management");
        usermanagement.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usermanagementActionPerformed(evt);
            }
        });
        dbmgmt.add(usermanagement);

        schedualmanagement.setText("Schedual Management");
        schedualmanagement.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                schedualmanagementActionPerformed(evt);
            }
        });
        dbmgmt.add(schedualmanagement);

        jMenuBar1.add(dbmgmt);

        webcams.setText("Webcams");

        allwebcams.setText("All Webcams");
        allwebcams.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                allwebcamsActionPerformed(evt);
            }
        });
        webcams.add(allwebcams);

        jMenuBar1.add(webcams);

        jMenu1.setText("Report Generation");

        aggregate_att.setText("Aggregate Attendance");
        aggregate_att.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aggregate_attActionPerformed(evt);
            }
        });
        jMenu1.add(aggregate_att);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Change Password");
        jMenu2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jMenu2.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jMenu2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu2MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel_main, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel_main, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        getAccessibleContext().setAccessibleName("Admin_main");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void studentmgmtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_studentmgmtActionPerformed
        // TODO add your handling code here:
        card.show(panel_main,"Student_dtls");
        panel_main.setSize(st.getPreferredSize());
        this.setSize(panel_main.getSize().width+20,panel_main.getSize().height+60);
    }//GEN-LAST:event_studentmgmtActionPerformed

    private void submgmtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submgmtActionPerformed
        // TODO add your handling code here:
        card.show(panel_main,"Subject_dtls");
        panel_main.setSize(sub.getPreferredSize());
        this.setSize(panel_main.getSize().width+20,panel_main.getSize().height+60);
    }//GEN-LAST:event_submgmtActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        this.setLocationRelativeTo(null);
        card.show(panel_main,"Webcam_dtls");
        panel_main.setSize(webcam.getPreferredSize());
        this.setSize(this.getMaximumSize().width,this.getMaximumSize().height);
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        this.getContentPane().setBackground(Color.WHITE);
        SwingUtilities.updateComponentTreeUI(this);
    }//GEN-LAST:event_formWindowOpened

    private void facultymgmtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_facultymgmtActionPerformed
        // TODO add your handling code here:
        card.show(panel_main,"Faculty_dtls");
        panel_main.setSize(fac.getPreferredSize());
        this.setSize(panel_main.getSize().width+20,panel_main.getSize().height+60);
    }//GEN-LAST:event_facultymgmtActionPerformed

    private void deparmentmgmtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deparmentmgmtActionPerformed
        // TODO add your handling code here:
        card.show(panel_main,"Department_dtls");
        panel_main.setSize(dept.getPreferredSize());
        this.setSize(panel_main.getSize().width+50,panel_main.getSize().height+60);
    }//GEN-LAST:event_deparmentmgmtActionPerformed

    private void usermanagementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usermanagementActionPerformed
        // TODO add your handling code here:
        card.show(panel_main,"User_dtls");
        panel_main.setSize(user.getPreferredSize());
        this.setSize(panel_main.getSize().width+70,panel_main.getSize().height+60);
    }//GEN-LAST:event_usermanagementActionPerformed

    private void schedualmanagementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_schedualmanagementActionPerformed
        // TODO add your handling code here:
        card.show(panel_main,"Schedual_dtls");
        panel_main.setSize(schedual.getPreferredSize());
        this.setSize(panel_main.getSize().width+30,panel_main.getSize().height+60);
    }//GEN-LAST:event_schedualmanagementActionPerformed

    private void allwebcamsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_allwebcamsActionPerformed
        // TODO add your handling code here:
        card.show(panel_main,"Webcam_dtls");
        panel_main.setSize(webcam.getSize());
        this.setSize(panel_main.getSize().width+30,panel_main.getSize().height+60);
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
    }//GEN-LAST:event_allwebcamsActionPerformed

    private void formWindowGainedFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowGainedFocus
        // TODO add your handling code here:    
        
    }//GEN-LAST:event_formWindowGainedFocus

    private void aggregate_attActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aggregate_attActionPerformed
        // TODO add your handling code here:
        card.show(panel_main,"ReportGen");
        panel_main.setSize(rptgn.getPreferredSize());
        this.setSize(this.getMaximumSize().width,this.getMaximumSize().height);
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
    }//GEN-LAST:event_aggregate_attActionPerformed

    private void jMenu2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu2MouseClicked
        // TODO add your handling code here:
        ChangePassword cp=new ChangePassword();
        cp.txt_userid.setText(adminid);
        cp.setVisible(true);
    }//GEN-LAST:event_jMenu2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Admin_Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new Admin_Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem aggregate_att;
    private javax.swing.JMenuItem allwebcams;
    private javax.swing.JMenu dbmgmt;
    private javax.swing.JMenuItem deparmentmgmt;
    private javax.swing.JMenuItem facultymgmt;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel panel_main;
    private javax.swing.JMenuItem schedualmanagement;
    private javax.swing.JMenuItem studentmgmt;
    private javax.swing.JMenuItem submgmt;
    private javax.swing.JMenuItem usermanagement;
    private javax.swing.JMenu webcams;
    // End of variables declaration//GEN-END:variables
}
