/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Pre_FRAMS;

import business_logic.*;
import java.awt.Color;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.io.InputStream;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;

/**
 *
 * @author Ray24
 */
public class Faculty_dtls extends javax.swing.JPanel {

    /**
     * Creates new form Faculty_dtls
     */
    FaceCam livefeed;
    BufferedImage img=null,defimg=null;
    department dept=null;
    user us=null;
    faculty fac=null;
    
    public Faculty_dtls() {
        initComponents();
        
        this.setBackground(Color.WHITE);
        jPanel1.setBackground(Color.decode("#838EDE"));
        
        dept=new department();
        us=new user();
        fac=new faculty();
        String d[]=dept.getAllDept();
        btn_takephoto.setEnabled(false);
        cmb_dept.removeAllItems();
        cmb_dept.addItem("Select Department");
        
        try {
        defimg = ImageIO.read(getClass().getResource("/images/not_available.jpg"));
            fac_img.setText("");
            fac_img.setIcon(new ImageIcon(defimg));
        } catch (IOException ex) {
            Logger.getLogger(Faculty_dtls.class.getName()).log(Level.SEVERE, null, ex);
        }
                    

        if(d.length!=0)
        {
            for(int i=0;i<d.length;i++)
            {
                cmb_dept.addItem(d[i]);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_webam = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txt_facid = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txt_fname = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txt_lname = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        cmb_dept = new javax.swing.JComboBox();
        fac_img = new javax.swing.JLabel();
        btn_view = new javax.swing.JButton();
        btn_save = new javax.swing.JButton();
        btn_update = new javax.swing.JButton();
        btn_delete = new javax.swing.JButton();
        btn_reset = new javax.swing.JButton();
        btn_takephoto = new javax.swing.JButton();
        btn_startcamera = new javax.swing.JButton();

        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                formFocusLost(evt);
            }
        });

        panel_webam.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Camera", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 0, 10))); // NOI18N
        panel_webam.setPreferredSize(new java.awt.Dimension(640, 480));

        javax.swing.GroupLayout panel_webamLayout = new javax.swing.GroupLayout(panel_webam);
        panel_webam.setLayout(panel_webamLayout);
        panel_webamLayout.setHorizontalGroup(
            panel_webamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 628, Short.MAX_VALUE)
        );
        panel_webamLayout.setVerticalGroup(
            panel_webamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 458, Short.MAX_VALUE)
        );

        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        jLabel1.setText("Faculty ID :");

        jLabel2.setText("First Name :");

        jLabel3.setText("Last Name :");

        jLabel4.setText("Department :");

        cmb_dept.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        fac_img.setText("Image of Faculty");
        fac_img.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        btn_view.setBackground(new java.awt.Color(131, 142, 222));
        btn_view.setText("View");
        btn_view.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_viewActionPerformed(evt);
            }
        });

        btn_save.setBackground(new java.awt.Color(131, 142, 222));
        btn_save.setText("Save");
        btn_save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_saveActionPerformed(evt);
            }
        });

        btn_update.setBackground(new java.awt.Color(131, 142, 222));
        btn_update.setText("Update");
        btn_update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_updateActionPerformed(evt);
            }
        });

        btn_delete.setBackground(new java.awt.Color(131, 142, 222));
        btn_delete.setText("Delete");
        btn_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_deleteActionPerformed(evt);
            }
        });

        btn_reset.setBackground(new java.awt.Color(131, 142, 222));
        btn_reset.setText("Reset");
        btn_reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_resetActionPerformed(evt);
            }
        });

        btn_takephoto.setBackground(new java.awt.Color(131, 142, 222));
        btn_takephoto.setText("Take Photo");
        btn_takephoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_takephotoActionPerformed(evt);
            }
        });

        btn_startcamera.setBackground(new java.awt.Color(131, 142, 222));
        btn_startcamera.setText("Start Camera");
        btn_startcamera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_startcameraActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(cmb_dept, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txt_facid)
                                    .addComponent(txt_fname)
                                    .addComponent(txt_lname, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(fac_img, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btn_view)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_save)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_update))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(btn_delete)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_reset))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(btn_takephoto)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_startcamera)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txt_facid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_fname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_lname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cmb_dept, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(fac_img, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_view)
                    .addComponent(btn_save)
                    .addComponent(btn_update))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_delete)
                    .addComponent(btn_reset))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_takephoto)
                    .addComponent(btn_startcamera))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panel_webam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panel_webam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btn_saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_saveActionPerformed
        // TODO add your handling code here:
        if(!txt_facid.getText().equals("")&&!txt_fname.getText().equals("")&&!txt_lname.getText().equals("")&&cmb_dept.getSelectedIndex()!=0)
        {
            boolean flg=us.insert(txt_facid.getText(),txt_fname.getText(),txt_lname.getText(),txt_facid.getText(),"Faculty");
            if(flg==true)
            {
                int l=0;
                InputStream is=null;
                if(img!=null)
                {
                    try
                    {
                    File f=new File("fac.jpg");
                    FileInputStream fis=new FileInputStream(f);
                    is=(InputStream)fis;
                    l=(int) f.length();
                    f.delete();
                    }
                    catch(FileNotFoundException ex)
                    {
                        System.out.println("File Error:"+ex.getMessage());
                    }
                }
                boolean flag=fac.insert(txt_facid.getText(),dept.getDeptID(cmb_dept.getSelectedItem().toString()),is,l);
                if(flg==true)
                {
                    JOptionPane.showMessageDialog(this,"Inserted successfully...");
                }
                else
                {
                    JOptionPane.showMessageDialog(this,"Can not insert...");
                }
            }
            else
            {
                JOptionPane.showMessageDialog(this,"Can not insert...");
            }
            
        }
        else
        {
            JOptionPane.showMessageDialog(this,"Enter all the details...");
        }
    }//GEN-LAST:event_btn_saveActionPerformed

    private void btn_resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_resetActionPerformed
        // TODO add your handling code here:
        txt_facid.setText("");
        txt_fname.setText("");
        txt_lname.setText("");
        //fac_img.setIcon(null);
        fac_img.setText("");
        fac_img.setIcon(new ImageIcon(defimg));
        cmb_dept.setSelectedIndex(0);
    }//GEN-LAST:event_btn_resetActionPerformed

    private void btn_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_deleteActionPerformed
        // TODO add your handling code here:
        fac_img.setText("");
        fac_img.setIcon(new ImageIcon(defimg));
        String uid=JOptionPane.showInputDialog(this,"Enter FacultyID :");
        if(uid!=null)
        {
        boolean flg=fac.delete(uid);
        if(flg==false)
        {
            
            JOptionPane.showMessageDialog(this,"FacultyID does not exist...");
        } 
        else
        {
            JOptionPane.showMessageDialog(this,"Deleted...");
        }
        }
    }//GEN-LAST:event_btn_deleteActionPerformed

    private void btn_updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_updateActionPerformed
        // TODO add your handling code here:
        if(!txt_facid.getText().equals("")&&!txt_fname.getText().equals("")&&!txt_lname.getText().equals("")&&cmb_dept.getSelectedIndex()!=0)
        {
            boolean flg=us.update(txt_facid.getText(),txt_fname.getText(),txt_lname.getText(),txt_facid.getText(),"Faculty");
            if(flg==true)
            {
                int l=0;
                InputStream is=null;
                if(fac_img.getIcon()!=null)
                {
                    try
                    {
                    File f=new File("fac.jpg");
                    ImageIcon im2=(ImageIcon) fac_img.getIcon();
                    Image im1=im2.getImage();
                    BufferedImage im=(BufferedImage) im1;
                    ImageIO.write(im,"jpg", f);
                    FileInputStream fis=new FileInputStream(f);
                    is=(InputStream)fis;
                    l=(int) f.length();
                    f.delete();
                    }
                    catch(FileNotFoundException ex)
                    {
                        System.out.println("File Error:"+ex.getMessage());
                    } catch (IOException ex) {
                        Logger.getLogger(Faculty_dtls.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
                boolean flag=fac.update(txt_facid.getText(),dept.getDeptID(cmb_dept.getSelectedItem().toString()),is,l);
                if(flg==true)
                {
                    JOptionPane.showMessageDialog(this,"Updated successfully...");
                }
                else
                {
                    JOptionPane.showMessageDialog(this,"Can not update...");
                }
            }
            else
            {
                JOptionPane.showMessageDialog(this,"Can not update...");
            }
            
        }
        else
        {
            JOptionPane.showMessageDialog(this,"Enter all the details...");
        }
    }//GEN-LAST:event_btn_updateActionPerformed

    private void btn_viewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_viewActionPerformed
        // TODO add your handling code here:
        String uid=JOptionPane.showInputDialog(this,"Enter FacultyID :");
        if(uid!=null)
        {
        String dep=dept.getDept(fac.getDeptID(uid));
        InputStream is=fac.getImage(uid);
        String fname=us.getFName(uid);
        String lname=us.getLName(uid);
        if(dep==null)
        {
            JOptionPane.showMessageDialog(this,"FacultyID does not exist...");
        }
        else
        {
            if(is!=null)
            {
            try {
                img=ImageIO.read(is);
                fac_img.setText("");
            fac_img.setIcon(new ImageIcon(img));
            } catch (IOException ex) {
                Logger.getLogger(Faculty_dtls.class.getName()).log(Level.SEVERE, null, ex);
            }
            }
            else
            {
                try {
                    BufferedImage i=ImageIO.read(getClass().getResource("/images/not_available.jpg"));
                    fac_img.setText("");
            fac_img.setIcon(new ImageIcon(i));
                } catch (IOException ex) {
                    Logger.getLogger(Faculty_dtls.class.getName()).log(Level.SEVERE, null, ex);
                }
                
            }
            txt_facid.setText(uid);
            txt_fname.setText(fname);
            txt_lname.setText(lname);
            cmb_dept.setSelectedItem(dep);
        }
        }
    }//GEN-LAST:event_btn_viewActionPerformed

    private void btn_takephotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_takephotoActionPerformed
        // TODO add your handling code here:
        img=livefeed.CaptureFace();
        fac_img.setText("");
        fac_img.setIcon(new ImageIcon(img));
        livefeed.closeDown();
        panel_webam.remove(livefeed);
        btn_takephoto.setEnabled(false);
        btn_startcamera.setEnabled(true);
        SwingUtilities.updateComponentTreeUI(this);
    }//GEN-LAST:event_btn_takephotoActionPerformed

    private void btn_startcameraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_startcameraActionPerformed
        // TODO add your handling code here:
//        if(btn_startcamera.getText().equals("Start Camera"))
//        {
//        btn_startcamera.setText("Stop Camera");
        livefeed=new FaceCam();
        livefeed.setSize(640,480);
        //livefeed.initcam();
        panel_webam.add(livefeed);
        btn_takephoto.setEnabled(true);
        btn_startcamera.setEnabled(false);
        SwingUtilities.updateComponentTreeUI(this);
//        }
//        if(btn_startcamera.getText().equals("Stop Camera"))
//        {
//            btn_startcamera.setText("Start Camera");
//            panel_webam.remove(livefeed);
//            livefeed.closeDown();
//            SwingUtilities.updateComponentTreeUI(panel_webam);
//            SwingUtilities.updateComponentTreeUI(this);
//        }
    }//GEN-LAST:event_btn_startcameraActionPerformed

    private void formFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_formFocusLost
        // TODO add your handling code here:
        livefeed.closeDown();
    }//GEN-LAST:event_formFocusLost


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_delete;
    private javax.swing.JButton btn_reset;
    private javax.swing.JButton btn_save;
    private javax.swing.JButton btn_startcamera;
    private javax.swing.JButton btn_takephoto;
    private javax.swing.JButton btn_update;
    private javax.swing.JButton btn_view;
    private javax.swing.JComboBox cmb_dept;
    private javax.swing.JLabel fac_img;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel panel_webam;
    private javax.swing.JTextField txt_facid;
    private javax.swing.JTextField txt_fname;
    private javax.swing.JTextField txt_lname;
    // End of variables declaration//GEN-END:variables
}
