/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Pre_FRAMS;

import javax.swing.*;
import business_logic.*;
import java.awt.Color;
/**
 *
 * @author Ray24
 */
public class Subject_dtls extends javax.swing.JPanel {

    /**
     * Creates new form Subject_dtls
     */
    subject sub=null;
    department dept=null;
    faculty fac=null;
    faculty_sub fac_sub=null;
    sub_dept sub_dep=null;
    public Subject_dtls() {
        initComponents();
        sub=new subject();
        dept=new department();
        fac=new faculty();
        fac_sub=new faculty_sub(); 
        sub_dep=new sub_dept();
        panel_Facu_Sub.setBackground(Color.decode("#838EDE"));
        panel_Sub.setBackground(Color.decode("#838EDE"));
        panel_Sub_Dept.setBackground(Color.decode("#838EDE"));
        this.setBackground(Color.WHITE);
        loadCombobox();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_Facu_Sub = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        cmb_subname_fac = new javax.swing.JComboBox();
        jLabel7 = new javax.swing.JLabel();
        cmb_dept_fac = new javax.swing.JComboBox();
        jLabel8 = new javax.swing.JLabel();
        cmb_facultyid = new javax.swing.JComboBox();
        btn_save_fac = new javax.swing.JButton();
        btn_reset_fac = new javax.swing.JButton();
        btn_delete_fac = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        cmb_facultyname = new javax.swing.JComboBox();
        panel_Sub_Dept = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        cmb_subname_dept = new javax.swing.JComboBox();
        cmb_dept_dept = new javax.swing.JComboBox();
        cmb_sem = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btn_save_dept = new javax.swing.JButton();
        btn_reset_dept = new javax.swing.JButton();
        btn_delete_dept = new javax.swing.JButton();
        panel_Sub = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txt_subid = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txt_subname = new javax.swing.JTextField();
        btn_save_main = new javax.swing.JButton();
        btn_view = new javax.swing.JButton();
        btn_delete_main = new javax.swing.JButton();
        btn_update = new javax.swing.JButton();
        btn_reset_main = new javax.swing.JButton();

        panel_Facu_Sub.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel6.setText("Subject Name :");

        cmb_subname_fac.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel7.setText("Department :");

        cmb_dept_fac.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmb_dept_fac.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmb_dept_facItemStateChanged(evt);
            }
        });

        jLabel8.setText("Faculty ID :");

        cmb_facultyid.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select FacultyID" }));
        cmb_facultyid.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmb_facultyidItemStateChanged(evt);
            }
        });

        btn_save_fac.setBackground(new java.awt.Color(131, 142, 222));
        btn_save_fac.setText("Save");
        btn_save_fac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_save_facActionPerformed(evt);
            }
        });

        btn_reset_fac.setBackground(new java.awt.Color(131, 142, 222));
        btn_reset_fac.setText("Reset");
        btn_reset_fac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_reset_facActionPerformed(evt);
            }
        });

        btn_delete_fac.setBackground(new java.awt.Color(131, 142, 222));
        btn_delete_fac.setText("Delete");
        btn_delete_fac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_delete_facActionPerformed(evt);
            }
        });

        jLabel9.setText("Faculty Name :");

        cmb_facultyname.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select FacultyName" }));

        javax.swing.GroupLayout panel_Facu_SubLayout = new javax.swing.GroupLayout(panel_Facu_Sub);
        panel_Facu_Sub.setLayout(panel_Facu_SubLayout);
        panel_Facu_SubLayout.setHorizontalGroup(
            panel_Facu_SubLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_Facu_SubLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_Facu_SubLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panel_Facu_SubLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cmb_dept_fac, 0, 110, Short.MAX_VALUE)
                    .addComponent(cmb_subname_fac, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panel_Facu_SubLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panel_Facu_SubLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cmb_facultyid, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cmb_facultyname, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(panel_Facu_SubLayout.createSequentialGroup()
                .addGap(115, 115, 115)
                .addComponent(btn_save_fac)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_reset_fac)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_delete_fac)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panel_Facu_SubLayout.setVerticalGroup(
            panel_Facu_SubLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_Facu_SubLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_Facu_SubLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(cmb_subname_fac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmb_facultyid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_Facu_SubLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmb_dept_fac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(cmb_facultyname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(18, 18, 18)
                .addGroup(panel_Facu_SubLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_save_fac)
                    .addComponent(btn_reset_fac)
                    .addComponent(btn_delete_fac))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panel_Sub_Dept.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel4.setText("Subject Name :");

        cmb_subname_dept.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cmb_dept_dept.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cmb_sem.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select Semester", "1", "2", "3", "4", "5", "6", "7", "8" }));

        jLabel3.setText("Department :");

        jLabel5.setText("Semester :");

        btn_save_dept.setBackground(new java.awt.Color(131, 142, 222));
        btn_save_dept.setText("Save");
        btn_save_dept.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_save_deptActionPerformed(evt);
            }
        });

        btn_reset_dept.setBackground(new java.awt.Color(131, 142, 222));
        btn_reset_dept.setText("Reset");
        btn_reset_dept.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_reset_deptActionPerformed(evt);
            }
        });

        btn_delete_dept.setBackground(new java.awt.Color(131, 142, 222));
        btn_delete_dept.setText("Delete");
        btn_delete_dept.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_delete_deptActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel_Sub_DeptLayout = new javax.swing.GroupLayout(panel_Sub_Dept);
        panel_Sub_Dept.setLayout(panel_Sub_DeptLayout);
        panel_Sub_DeptLayout.setHorizontalGroup(
            panel_Sub_DeptLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_Sub_DeptLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_Sub_DeptLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_Sub_DeptLayout.createSequentialGroup()
                        .addGroup(panel_Sub_DeptLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5))
                        .addGap(18, 18, 18)
                        .addGroup(panel_Sub_DeptLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cmb_dept_dept, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cmb_sem, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cmb_subname_dept, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(panel_Sub_DeptLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btn_save_dept)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_reset_dept)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_delete_dept)
                        .addGap(4, 4, 4)))
                .addGap(6, 6, 6))
        );
        panel_Sub_DeptLayout.setVerticalGroup(
            panel_Sub_DeptLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_Sub_DeptLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_Sub_DeptLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cmb_subname_dept, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_Sub_DeptLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmb_dept_dept, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_Sub_DeptLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmb_sem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(panel_Sub_DeptLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_save_dept)
                    .addComponent(btn_reset_dept)
                    .addComponent(btn_delete_dept))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        panel_Sub.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel1.setText("Subject ID :");

        jLabel2.setText("Subject Name :");

        btn_save_main.setBackground(new java.awt.Color(131, 142, 222));
        btn_save_main.setText("Save");
        btn_save_main.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_save_mainActionPerformed(evt);
            }
        });

        btn_view.setBackground(new java.awt.Color(131, 142, 222));
        btn_view.setText("View");
        btn_view.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_viewActionPerformed(evt);
            }
        });

        btn_delete_main.setBackground(new java.awt.Color(131, 142, 222));
        btn_delete_main.setText("Delete");
        btn_delete_main.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_delete_mainActionPerformed(evt);
            }
        });

        btn_update.setBackground(new java.awt.Color(131, 142, 222));
        btn_update.setText("Update");
        btn_update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_updateActionPerformed(evt);
            }
        });

        btn_reset_main.setBackground(new java.awt.Color(131, 142, 222));
        btn_reset_main.setText("Reset");
        btn_reset_main.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_reset_mainActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel_SubLayout = new javax.swing.GroupLayout(panel_Sub);
        panel_Sub.setLayout(panel_SubLayout);
        panel_SubLayout.setHorizontalGroup(
            panel_SubLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_SubLayout.createSequentialGroup()
                .addGroup(panel_SubLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_SubLayout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(btn_delete_main)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_reset_main))
                    .addGroup(panel_SubLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btn_view)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_save_main)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_update))
                    .addGroup(panel_SubLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(panel_SubLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(11, 11, 11)
                        .addGroup(panel_SubLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_subname)
                            .addGroup(panel_SubLayout.createSequentialGroup()
                                .addComponent(txt_subid, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 52, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        panel_SubLayout.setVerticalGroup(
            panel_SubLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_SubLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_SubLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txt_subid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_SubLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_subname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(panel_SubLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_save_main)
                    .addComponent(btn_view)
                    .addComponent(btn_update))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_SubLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_delete_main)
                    .addComponent(btn_reset_main))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(panel_Facu_Sub, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(panel_Sub, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(panel_Sub_Dept, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panel_Sub_Dept, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panel_Sub, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panel_Facu_Sub, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btn_reset_deptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_reset_deptActionPerformed
        // TODO add your handling code here:
        cmb_dept_dept.setSelectedIndex(0);
        cmb_sem.setSelectedIndex(0);
        cmb_subname_dept.setSelectedIndex(0);
    }//GEN-LAST:event_btn_reset_deptActionPerformed

    private void btn_delete_deptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_delete_deptActionPerformed
        // TODO add your handling code here:
        String uid=JOptionPane.showInputDialog(this,"Enter SubjectID :");
        if(uid!=null)
        {
        boolean flg=sub_dep.delete(uid);
        if(flg==false)
        {
            JOptionPane.showMessageDialog(this,"Subject ID does not exist...");
        } 
        else
        {
            JOptionPane.showMessageDialog(this,"Deleted...");
        }
        }
    }//GEN-LAST:event_btn_delete_deptActionPerformed

    private void btn_reset_facActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_reset_facActionPerformed
        // TODO add your handling code here:
        cmb_dept_fac.setSelectedIndex(0);
        cmb_facultyid.setSelectedIndex(0);
        cmb_facultyname.setSelectedIndex(0);
        cmb_subname_fac.setSelectedIndex(0);
    }//GEN-LAST:event_btn_reset_facActionPerformed

    private void btn_delete_facActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_delete_facActionPerformed
        // TODO add your handling code here:
        String fid=JOptionPane.showInputDialog(this,"Enter FacultyID :");
        if(fid!=null)
        {
        String sid=JOptionPane.showInputDialog(this,"Enter SubjectID :");
        if(sid!=null)
        {
        boolean flg=fac_sub.delete(fid, sid);
        if(flg==false)
        {
            JOptionPane.showMessageDialog(this,"FacultyID or SubjectID does not match...");
        } 
        else
        {
            JOptionPane.showMessageDialog(this,"Deleted...");
        }
        }
        }
    }//GEN-LAST:event_btn_delete_facActionPerformed

    private void btn_viewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_viewActionPerformed
        // TODO add your handling code here:
        String uid=JOptionPane.showInputDialog(this,"Enter SubjectID :");
        if(uid!=null)
        {
        String flg=sub.getSub(uid);
        
        if(flg==null)
        {
            JOptionPane.showMessageDialog(this,"Subject ID does not exist...");
        }
        else
        {
            txt_subid.setText(uid);
            txt_subname.setText(flg);
        }
        }
    }//GEN-LAST:event_btn_viewActionPerformed

    private void loadCombobox()
    {
        String allsub[]=sub.getAllSub();
        String alldept[]=dept.getAllDept();
        cmb_dept_dept.removeAllItems();
            cmb_dept_fac.removeAllItems();
            cmb_dept_dept.addItem("Select Department");
            cmb_dept_fac.addItem("Select Department");
        if(alldept.length!=0)
        {
            
            for(int i=0;i<alldept.length;i++)
            {
                cmb_dept_dept.addItem(alldept[i]);
                cmb_dept_fac.addItem(alldept[i]);
            }
        }
        cmb_subname_dept.removeAllItems();
            cmb_subname_fac.removeAllItems();
            cmb_subname_dept.addItem("Select Subject");
            cmb_subname_fac.addItem("Select Subject");
        if(allsub.length!=0)
        {
            
            for(int i=0;i<allsub.length;i++)
            {
                cmb_subname_dept.addItem(allsub[i]);
                cmb_subname_fac.addItem(allsub[i]);
            }
        }
    }
    private void btn_reset_mainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_reset_mainActionPerformed
        // TODO add your handling code here:
        txt_subid.setText("");
        txt_subname.setText("");
    }//GEN-LAST:event_btn_reset_mainActionPerformed

    private void btn_delete_mainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_delete_mainActionPerformed
        // TODO add your handling code here:
        String uid=JOptionPane.showInputDialog(this,"Enter SubjetID :");
        if(uid!=null)
        {
        boolean flg=sub.delete(uid);
        if(flg==false)
        {
            JOptionPane.showMessageDialog(this,"Subject ID does not exist...");
        } 
        else
        {
            JOptionPane.showMessageDialog(this,"Deleted...");
        }
        }
    }//GEN-LAST:event_btn_delete_mainActionPerformed

    private void btn_updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_updateActionPerformed
        // TODO add your handling code here:
        if(!txt_subid.getText().equals("") && !txt_subname.getText().equals(""))
        {
        boolean flg=sub.update(txt_subid.getText(),txt_subname.getText());
        if(flg==false)
        {
            JOptionPane.showMessageDialog(this,"Subject ID does not exist...");
        }
        else
        {
            JOptionPane.showMessageDialog(this,"Updated successfully...");
            loadCombobox();
        }
        }
        else
        {
            JOptionPane.showMessageDialog(this,"Enter all the details...");
        }
    }//GEN-LAST:event_btn_updateActionPerformed

    private void btn_save_mainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_save_mainActionPerformed
        // TODO add your handling code here:
        if(!txt_subid.getText().equals("") && !txt_subname.getText().equals(""))
        {
        boolean flg=sub.insert(txt_subid.getText(),txt_subname.getText());
        if(flg==false)
        {
            JOptionPane.showMessageDialog(this,"Can't insert details...");
        }
        else
        {
            JOptionPane.showMessageDialog(this,"Inserted successfully...");
            loadCombobox();
        }
        }
        else
        {
            JOptionPane.showMessageDialog(this,"Enter all the details...");
        }
    }//GEN-LAST:event_btn_save_mainActionPerformed

    private void btn_save_deptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_save_deptActionPerformed
        // TODO add your handling code here:
        if(cmb_dept_dept.getSelectedIndex()!=0 && cmb_sem.getSelectedIndex()!=0 && cmb_subname_dept.getSelectedIndex()!=0)
        {
            String deptid=dept.getDeptID(cmb_dept_dept.getSelectedItem().toString());
            String subid=sub.getSubID(cmb_subname_dept.getSelectedItem().toString());
            boolean flg=sub_dep.insert(subid, deptid, Integer.parseInt((String) cmb_sem.getSelectedItem()));
            if(flg==false)
            {
                JOptionPane.showMessageDialog(this,"Can not insert details...");
            }
            else
            {
                JOptionPane.showMessageDialog(this,"Inserted successfully...");
            }
        }
        else
        {
            JOptionPane.showMessageDialog(this,"Select all the details...");
        }
    }//GEN-LAST:event_btn_save_deptActionPerformed

    private void btn_save_facActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_save_facActionPerformed
        // TODO add your handling code here:
        if(cmb_dept_fac.getSelectedIndex()!=0 && cmb_facultyid.getSelectedIndex()!=0 && cmb_subname_fac.getSelectedIndex()!=0)
        {
            String subid=sub.getSubID(cmb_subname_fac.getSelectedItem().toString());
            String facid=cmb_facultyid.getSelectedItem().toString();
            boolean flg=fac_sub.insert(facid, subid);
            if(flg==false)
            {
                JOptionPane.showMessageDialog(this,"Can not insert details...");
            }
            else
            {
                JOptionPane.showMessageDialog(this,"Inserted successfully...");
            }
        }
        else
        {
            JOptionPane.showMessageDialog(this,"Select all the details...");
        }
    }//GEN-LAST:event_btn_save_facActionPerformed

    private void cmb_dept_facItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmb_dept_facItemStateChanged
        // TODO add your handling code here:
        if(evt.getStateChange()==java.awt.event.ItemEvent.SELECTED)
        {
        if(cmb_dept_fac.getSelectedIndex()!=0)
        {
            String deptid=dept.getDeptID(cmb_dept_fac.getSelectedItem().toString());
            String facid[]=fac.getFacultyIDbyDept(deptid);
            cmb_facultyid.removeAllItems();
            cmb_facultyid.addItem("Select FacultyID");
            cmb_facultyname.removeAllItems();
            cmb_facultyname.addItem("Select FacultyName");
            if(facid.length!=0)
            {
                user us=new user();
                for(int i=0;i<facid.length;i++)
                {
                    String facname=us.getFName(facid[i])+" "+us.getLName(facid[i]);
                    if(facid[i]!=null)
                    {
                        cmb_facultyid.addItem(facid[i]);
                        if(facname!=null)
                           {cmb_facultyname.addItem(facname);}
                    }
                    
                }
            }
        }
        }
    }//GEN-LAST:event_cmb_dept_facItemStateChanged

    private void cmb_facultyidItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmb_facultyidItemStateChanged
        // TODO add your handling code here:
        if(evt.getStateChange()==java.awt.event.ItemEvent.SELECTED)
        {
        if(cmb_facultyid.getSelectedIndex()!=0)
        {
            user us=new user();
            String facname=us.getFName(cmb_facultyid.getSelectedItem().toString())+" "+us.getLName(cmb_facultyid.getSelectedItem().toString());
            if(facname!=null)
            {cmb_facultyname.setSelectedItem(facname);}
        }
        }
    }//GEN-LAST:event_cmb_facultyidItemStateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_delete_dept;
    private javax.swing.JButton btn_delete_fac;
    private javax.swing.JButton btn_delete_main;
    private javax.swing.JButton btn_reset_dept;
    private javax.swing.JButton btn_reset_fac;
    private javax.swing.JButton btn_reset_main;
    private javax.swing.JButton btn_save_dept;
    private javax.swing.JButton btn_save_fac;
    private javax.swing.JButton btn_save_main;
    private javax.swing.JButton btn_update;
    private javax.swing.JButton btn_view;
    private javax.swing.JComboBox cmb_dept_dept;
    private javax.swing.JComboBox cmb_dept_fac;
    private javax.swing.JComboBox cmb_facultyid;
    private javax.swing.JComboBox cmb_facultyname;
    private javax.swing.JComboBox cmb_sem;
    private javax.swing.JComboBox cmb_subname_dept;
    private javax.swing.JComboBox cmb_subname_fac;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel panel_Facu_Sub;
    private javax.swing.JPanel panel_Sub;
    private javax.swing.JPanel panel_Sub_Dept;
    private javax.swing.JTextField txt_subid;
    private javax.swing.JTextField txt_subname;
    // End of variables declaration//GEN-END:variables
}
