/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Server_Client;

import java.awt.Color;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.net.Socket;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Ray24
 */
public class ChangePassword extends javax.swing.JFrame {

    /**
     * Creates new form ForgotPassword
     */
    public Socket s=null;
public ObjectOutputStream oos=null;
public ObjectInputStream ois=null;

    public ChangePassword() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        main_panel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txt_userid = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btn_confirm = new javax.swing.JButton();
        btn_reset = new javax.swing.JButton();
        btn_cancel = new javax.swing.JButton();
        txt_cur_pwd = new javax.swing.JPasswordField();
        txt_new_pwd = new javax.swing.JPasswordField();
        txt_cnf_pwd = new javax.swing.JPasswordField();
        lbl_cur_label = new javax.swing.JLabel();
        lbl_cnf_label = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        main_panel.setBackground(new java.awt.Color(131, 142, 222));
        main_panel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        jLabel1.setText("User ID :");

        jLabel2.setText("Current Password :");

        jLabel3.setText("Confirm Password :");

        jLabel4.setText("New Password :");

        btn_confirm.setText("Change");
        btn_confirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_confirmActionPerformed(evt);
            }
        });

        btn_reset.setText("Reset");
        btn_reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_resetActionPerformed(evt);
            }
        });

        btn_cancel.setText("Cancel");
        btn_cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cancelActionPerformed(evt);
            }
        });

        txt_cur_pwd.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_cur_pwdFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_cur_pwdFocusLost(evt);
            }
        });

        txt_cnf_pwd.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_cnf_pwdKeyReleased(evt);
            }
        });

        lbl_cur_label.setText("jLabel5");

        lbl_cnf_label.setText("jLabel5");

        javax.swing.GroupLayout main_panelLayout = new javax.swing.GroupLayout(main_panel);
        main_panel.setLayout(main_panelLayout);
        main_panelLayout.setHorizontalGroup(
            main_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(main_panelLayout.createSequentialGroup()
                .addGroup(main_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(main_panelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(main_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, main_panelLayout.createSequentialGroup()
                                .addGroup(main_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btn_confirm)
                                    .addComponent(jLabel2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btn_reset)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_cancel))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, main_panelLayout.createSequentialGroup()
                                .addGroup(main_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel3))
                                .addGap(21, 21, 21)
                                .addGroup(main_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txt_new_pwd, javax.swing.GroupLayout.DEFAULT_SIZE, 132, Short.MAX_VALUE)
                                    .addComponent(txt_cnf_pwd))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lbl_cnf_label))))
                    .addGroup(main_panelLayout.createSequentialGroup()
                        .addGap(124, 124, 124)
                        .addGroup(main_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_userid, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(main_panelLayout.createSequentialGroup()
                                .addComponent(txt_cur_pwd, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lbl_cur_label)))))
                .addGap(111, 119, Short.MAX_VALUE))
        );
        main_panelLayout.setVerticalGroup(
            main_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(main_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(main_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txt_userid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(main_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txt_cur_pwd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_cur_label))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(main_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txt_new_pwd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(main_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txt_cnf_pwd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_cnf_label))
                .addGap(30, 30, 30)
                .addGroup(main_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_confirm)
                    .addComponent(btn_reset)
                    .addComponent(btn_cancel))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(main_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(main_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_confirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_confirmActionPerformed
        //TODO add your handling code here:
        String newp=new String(txt_new_pwd.getPassword());
        try {
            oos.writeObject(newp);
            String flg=(String) ois.readObject();
            if(flg.equals("true"))
            {
                JOptionPane.showMessageDialog(this,"Password Changed...");
            }
            else
                {
                JOptionPane.showMessageDialog(this,"Can't Change Password...");
                
            }
        } catch (IOException | ClassNotFoundException ex) {
            Logger.getLogger(ChangePassword.class.getName()).log(Level.SEVERE, null, ex);
        }
        txt_cnf_pwd.setText("");
        txt_cur_pwd.setText("");
        txt_new_pwd.setText("");
        btn_confirm.setEnabled(false);
        lbl_cnf_label.setVisible(false);
        lbl_cur_label.setVisible(false);
    }//GEN-LAST:event_btn_confirmActionPerformed

    private void btn_resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_resetActionPerformed
        // TODO add your handling code here:
        
        txt_cnf_pwd.setText("");
        txt_cur_pwd.setText("");
        txt_new_pwd.setText("");
        btn_confirm.setEnabled(false);
        lbl_cnf_label.setVisible(false);
        
        try {
            // TODO add your handling code here:
            oos.writeObject("break");
            oos.writeObject("Change Password");
        } catch (IOException ex) {
            Logger.getLogger(ChangePassword.class.getName()).log(Level.SEVERE, null, ex);
        }lbl_cur_label.setVisible(false);
    }//GEN-LAST:event_btn_resetActionPerformed

    private void btn_cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cancelActionPerformed
        try {
            // TODO add your handling code here:
            oos.writeObject("break");
        } catch (IOException ex) {
            Logger.getLogger(ChangePassword.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.dispose();
//        Frame[] f=getFrames();
//        for(int i=0;i<f.length;i++)
//        {
//            String sd=f[i].getName();
//            if(sd.equals("Student_Home"))
//            {
//                f[i].setEnabled(true);
//            }
//        }
    }//GEN-LAST:event_btn_cancelActionPerformed

    private void txt_cur_pwdFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_cur_pwdFocusLost
        // TODO add your handling code here:
        String old=new String(txt_cur_pwd.getPassword());
        
        if(old!=null)
        {
        try{
           
            
            oos.writeObject(old);
            String status=(String)ois.readObject();
            if(status.equals("Success"))
            {
                lbl_cur_label.setText("Correct Password");
                lbl_cur_label.setForeground(Color.GREEN);
                lbl_cur_label.setVisible(true);
            }
            else
            {
                lbl_cur_label.setText("Incorrect Password");
                lbl_cur_label.setForeground(Color.RED);
                lbl_cur_label.setVisible(true);
                btn_confirm.setEnabled(false);
            }
        }
        catch(Exception e)
        {
            e.printStackTrace();
        }
        }
    }//GEN-LAST:event_txt_cur_pwdFocusLost

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        lbl_cnf_label.setVisible(false);
        lbl_cur_label.setVisible(false);
        btn_confirm.setEnabled(false);
        txt_userid.setFocusable(false);
//        Frame[] f=getFrames();
//        for(int i=0;i<f.length;i++)
//        {
//            String sd=f[i].getName();
//            if(sd.equals("Student_Home"))
//            {
//                f[i].setEnabled(false);
//            }
//        }
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_formWindowOpened

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            oos.writeObject("break");
        } catch (IOException ex) {
            Logger.getLogger(ChangePassword.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.dispose();
//        Frame[] f=getFrames();
//        for(int i=0;i<f.length;i++)
//        {
//            String sd=f[i].getName();
//            if(sd.equals("Student_Home"))
//            {
//                f[i].setEnabled(true);
//            }
//        }
    }//GEN-LAST:event_formWindowClosed

    private void txt_cur_pwdFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_cur_pwdFocusGained
        // TODO add your handling code here:
        if(lbl_cur_label.isVisible()&&lbl_cur_label.getText().equals("Incorrect Password"))
        {
        try {
            // TODO add your handling code here:
            oos.writeObject("break");
            oos.writeObject("Change Password");
        } catch (IOException ex) {
            Logger.getLogger(ChangePassword.class.getName()).log(Level.SEVERE, null, ex);
        }
        }
    }//GEN-LAST:event_txt_cur_pwdFocusGained

    private void txt_cnf_pwdKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_cnf_pwdKeyReleased
        // TODO add your handling code here:
        String newp=new String(txt_new_pwd.getPassword());
        String cnf=new String(txt_cnf_pwd.getPassword());
        
        if(cnf!=null)
        {
            System.out.println("newp="+newp+",cnf="+cnf);
        if(newp.equals(cnf))
        {
            lbl_cnf_label.setText("Matched");
            lbl_cnf_label.setForeground(Color.GREEN);
            lbl_cnf_label.setVisible(true);
            btn_confirm.setEnabled(true);
        }
        else
        {
            lbl_cnf_label.setText("Not Matched");
            lbl_cnf_label.setForeground(Color.RED);
            lbl_cnf_label.setVisible(true);
            btn_confirm.setEnabled(false);
        }
        }
    }//GEN-LAST:event_txt_cnf_pwdKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ChangePassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ChangePassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ChangePassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ChangePassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ChangePassword().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_cancel;
    private javax.swing.JButton btn_confirm;
    private javax.swing.JButton btn_reset;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel lbl_cnf_label;
    private javax.swing.JLabel lbl_cur_label;
    private javax.swing.JPanel main_panel;
    private javax.swing.JPasswordField txt_cnf_pwd;
    private javax.swing.JPasswordField txt_cur_pwd;
    private javax.swing.JPasswordField txt_new_pwd;
    public javax.swing.JTextField txt_userid;
    // End of variables declaration//GEN-END:variables
}
